### ISSUE TITLE
Comment:Step-Basic-Rest-client

### ISSUE THREAD

**Issue by rjpalermo1** [eddyystop/feathers-an-introduction#2]
Comment:Step-Basic-Rest-client

>Feathers "ah-ha" moment. We can run exactly the same code on the frontend as on the server. We can code the frontend as if the database was sitting on it. That's part of the magic of Feathers, and it makes frontend development significantly simpler.

`We can run exactly the same code on the frontend as on the server`

Does this mean that the code has to be duplicated on the front end like we did on the server?  Or does the client now contain the code, pass it to the server and the server just accept it and process it?

**Comment by eddyystop** [comment]
This repo is deprecated. It's been absorbed into feathersjs/feathers-guides.

The latter. The code need only run on the client. Feathers-client calls the server and  Feathers-server executes.
