### ISSUE TITLE
Comment:Step-Basic-Hooks-1

### ISSUE THREAD

**Issue by rjpalermo1** [eddyystop/feathers-an-introduction#5]
Comment:Step-Basic-Hooks-1

>- validateSchema(userSchema(), Ajv)
>Validate the data we are to add using ajv. The service's JSON schema is provided by function >userSchema.

Assuming `Ajv` is installed in the `feathers-hooks-common` package?

If so, would be nice to have a link to a page that shows all the packages pre-installed when you use this `feathers-hooks-common` to avoid confusion or wondering if I need to install it when you point out a package that is being used.

**Comment by rjpalermo1** [comment]
well - after reading through again see you addressed this 

- const { validateSchema, setCreatedAt, setUpdatedAt, unless, remove } = commonHooks;
> Feathers comes with a library of useful hooks. Here we get some common hooks from feathers-hooks-common. More specialized hooks come bundled with their specialized packages, such as with feathers-authentication-local.

Maybe a link to a page with the common hooks linking the packages would be helpful...

**Comment by eddyystop** [comment]
[Ajv](https://github.com/epoberezkin/ajv) is not included `feathers-hooks-common`. Including it would bloat the hooks-common for people not using `validateSchema`.
